spring:
  application:
    name: ottShare

  datasource:
    url: jdbc:mysql://mysql-container:3306/ottShare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        type: trace

  data:
    redis:
      host: redis
      port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /

    queue:
      name: chat.queue
    exchange:
      name: chat.exchange
    routing:
      key: chat.key

server:
  port: 8080

jwt:
  secret: MTQyQUQzMzEzRTY4QjY1NzhGMTM1QjMyQzFBNzg1QUJDREUxMjM0NTY3ODkwMTIzNDU=
  expiration: 3600000
  refreshExpiration: 86400000