spring:
  application:
    name: ottShare

  datasource:
    url: jdbc:mysql://localhost:3306/ottShare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true  # SQL 쿼리 로그 출력 (선택)
        use_sql_comments: true  # SQL 주석 표시 (선택)
        type: trace  # 바인딩된 파라미터 값 출력 (선택)

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: rabbitmq-container  # Docker 컨테이너명으로 변경
    port: 5672
    username: guest
    password: guest
    virtual-host: /

    queue:
      name: chat.queue  # 사용할 queue 이름
    exchange:
      name: chat.exchange  # 사용할 exchange 이름
    routing:
      key: chat.key  # 라우팅 키 설정

server:
  port: 8080

jwt:
  secret: MTQyQUQzMzEzRTY4QjY1NzhGMTM1QjMyQzFBNzg1QUJDREUxMjM0NTY3ODkwMTIzNDU=
  expiration: 3600000  # Access Token 만료 시간 (1시간)
  refreshExpiration: 86400000  # Refresh Token 만료 시간 (24시간)