spring:
  application:
    name: ottShare

  datasource:
    url: jdbc:mysql://mysql-container:3306/ottShare
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

  data:
    redis:
      host: redis
      port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    queue:
      name: chat.queue
    exchange:
      name: chat.exchange

  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration

server:
  port: 8081

jwt:
  secret: MTQyQUQzMzEzRTY4QjY1NzhGMTM1QjMyQzFBNzg1QUJDREUxMjM0NTY3ODkwMTIzNDU=
  expiration: 3600000
  refreshExpiration: 86400000