spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/ottshare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    queue:
      name: chat.queue
    exchange:
      name: chat.exchange
